### ISSUE TITLE
Error on sign-on to demo app when deploying to PingOne EU - hardcoded `pingone.com` likely

### ISSUE THREAD

**Issue by patrickcping** [pingidentity-developers-experience/ping-p1-terraform-sample-apps#26]
- BXR TF deploys fine
- K8s applications have correct base URLs in their configuration
```
REACT_APP_AUTHPATH:      https://auth.pingone.eu                                                                                                                                                   REACT_APP_APIPATH:       https://api.pingone.eu/v1
```
- Attempt sign-on at app URL (e.g. https://bxretail-patrickc-demo.ping-devops.com/app/)
- Browser trace shows a call to `https://auth.pingone.com/<<env_id>>/as/.well-known/openid-configuration` - incorrect `.com` address
- Browser trace shows a call to `https://auth.pingone.com/<<env_id>>/as/authorize?respo....` - incorrect `.com` address
- Results in "The request could not be completed. The requested resource was not found." on PingOne branded screens, as the url for the environment is incorrect

**Comment by michaelsanchez-pingidentity** [comment]
Evaluating to fix this sprint (Ugarit). Story #185372445.

**Comment by michaelsanchez-pingidentity** [comment]
Don't have root cause yet, but the issue is that somehow the TF local var didn't overwrite the .env file when the container spun up. So the default persisted.

**Comment by michaelsanchez-pingidentity** [comment]
The sample app was updated to use the new OIDC SDK and an env var was missed in the update. hotfix coming Monday.

**Comment by michaelsanchez-pingidentity** [comment]
Additionally updated the CSP with missing TLDs.

**Comment by michaelsanchez-pingidentity** [comment]
Pushed new image for latest.
